#!/usr/bin/python

"""Amulet tests on a basic nova cloud controller deployment on
   utopic-juno."""

from basic_deployment import NovaCCBasicDeployment

if __name__ == '__main__':
    deployment = NovaCCBasicDeployment(series='utopic')
    deployment.run_tests()
