#!/usr/bin/python

"""Amulet tests on a basic nova cloud controller deployment on
   trusty-mitaka."""

from basic_deployment import NovaCCBasicDeployment

if __name__ == '__main__':
    deployment = NovaCCBasicDeployment(series='trusty',
                                       openstack='cloud:trusty-mitaka',
                                       source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
