#!/usr/bin/python

"""Amulet tests on a basic nova cloud controller deployment on
   xenial-mitaka."""

from basic_deployment import NovaCCBasicDeployment

if __name__ == '__main__':
    deployment = NovaCCBasicDeployment(series='xenial')
    deployment.run_tests()
