#!/usr/bin/python

"""Amulet tests on a basic nova cloud controller deployment on
   precise-grizzly."""

from basic_deployment import NovaCCBasicDeployment

if __name__ == '__main__':
    deployment = NovaCCBasicDeployment(series='precise',
                                       openstack='cloud:precise-grizzly',
                                       source='cloud:precise-updates/grizzly')
    deployment.run_tests()
