#!/bin/bash

CHARM="nova-cloud-controller"
CONF_DIR="/etc/nova"

SERVICES="nova-api-ec2 nova-api-os-compute nova-objectstore nova-cert nova-scheduler"

# If we have a relation to nova-volume-service, we'll also manage its API
# endpoint here.
n_vol=$(relation-ids nova-volume-service)
if [[ -n "$n_vol" ]] ; then
  SERVICES="$SERVICES nova-api-os-volume"
  dpkg -l | grep -q nova-api-os-volume || apt-get -y install nova-api-os-volume
fi

PACKAGES="$SERVICES python-mysqldb python-keystone uuid"

NOVA_CONF=$(config-get nova-config)
API_CONF="/etc/nova/api-paste.ini"

if [[ -e $CHARM_DIR/lib/nova/nova-common ]] ; then
  . $CHARM_DIR/lib/nova/nova-common
else
  juju-log "Couldn't load $CHARM_DIR/lib/nova/nova-common" && exit 1
fi
